strategy: dockerfile
source:
- file: ./Dockerfile.stage1
  common: true
- file: ./Dockerfile.stage2
  common: true
- file: ./Dockerfile.stage3
  common: true
- ./Dockerfile.stage4

python:
  versions:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

package:
  versions:
  - 11.0.0
  - 12.0.0
  - 12.1.0
