strategy: dockerfile
source:
- file: ./Dockerfile.stage1
  common: true
- ./Dockerfile.stage2
disable: true

python:
  versions:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

package:
  versions:
  - latest