strategy: dockerfile
source:
- file: ./Dockerfile.stage1
  common: true
- file: ./Dockerfile.stage2

python:
  versions:
  - "3.10"
  - "3.11"
  - "3.12"
  - "3.13"
  - "3.13t"

package:
  versions: latest
