strategy: dockerfile
disable: true
source:
- file: ./Dockerfile.stage1
  common: true
- ./Dockerfile.stage2

python:
  versions:
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"

package:
  versions: latest
